Vagrant.configure("2") do |config|
    config.vm.define "client2" do |client|
      client.vm.box = "geerlingguy/centos7"
      client.vm.network "private_network", type: "static", ip: "192.168.99.12"
      client.vm.hostname = "client2"
      client.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.name = "client2"
        v.memory = 512
        v.cpus = 1
      end
      client.vm.provision :shell do |shell|
        shell.path = "install_ansible.sh"
        shell.args = ["master", "192.168.99.12"]
        shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
        
      end
    end
end