Vagrant.configure("2") do |config|
  # Configure the load balancer machine
  config.vm.define "node-manager" do |nodm|
    nodm.vm.box = "debian/bullseye64"
    nodm.vm.hostname = "node-manager"
    nodm.vm.network "private_network", ip: "192.168.122.10"
  end

  # Configure the load balancer machine
  config.vm.define "serveur-1" do |server1|
    server1.vm.box = "debian/bullseye64"
    server1.vm.hostname = "serveur-1"
    server1.vm.network "private_network", ip: "192.168.122.11"
  end

  # Configure the load balancer machine
  config.vm.define "serveur-2" do |server2|
    server2.vm.box = "debian/bullseye64"
    server2.vm.hostname = "serveur-2"
    server2.vm.network "private_network", ip: "192.168.122.12"
  end
end
