Vagrant.configure("2") do |config|
    config.vm.define "webserver" do |webserver|
      webserver.vm.box = "ubuntu/bionic64"  # Use Ubuntu 18.04 LTS image
      webserver.vm.network "private_network", type: "static", ip: "192.168.100.10"
      webserver.vm.hostname = "webserver-ubuntu"
      webserver.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.name = "webserver-ubuntu"
        v.memory = 512
        v.cpus = 1
      end
      webserver.vm.provision :shell, inline: <<-SHELL
        # Inline shell commands here
      SHELL
      webserver.vm.provision :shell do |shell|
        shell.path = "port_forwarding.sh"
        shell.args = ["webserver", "192.168.100.10"]
      end
    end
  end
  