Vagrant.configure("2") do |config|
    # Configure the load balancer machine
    config.vm.define "lb" do |lb|
        lb.vm.box = "ubuntu/xenial64"
        lb.vm.network "private_network", ip: "10.0.0.10"
    end

    # Configure the load balancer machine
    config.vm.define "web1" do |web1|
        web1.vm.box = "ubuntu/xenial64"
        web1.vm.network "private_network", ip: "10.0.0.11"
    end

    # Configure the load balancer machine
    config.vm.define "web2" do |web2|
        web2.vm.box = "ubuntu/xenial64"
        web2.vm.network "private_network", ip: "10.0.0.12"
    end
end