Vagrant.configure("2") do |config|
    config.vm.define "jenkinsserver" do |jenkinsserver|
      jenkinsserver.vm.box = "debian/buster64"
      jenkinsserver.vm.hostname = "jenkinsserver"
      jenkinsserver.vm.network :private_network, ip: "192.168.15.10"
    
      jenkinsserver.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.memory = 2048
        v.name = "jenkinsserver"
        v.cpus = 2
      end
    
      jenkinsserver.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y openjdk-11-jdk
        
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
        sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
        apt-get update
        apt-get install -y jenkins
        systemctl enable jenkins
        systemctl start jenkins
        
        apt-get install -y ansible
        
        apt-get remove -y docker docker-engine docker.io containerd runc
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        systemctl enable docker
        systemctl start docker
        
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      SHELL
    end
  end
  