# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "minikube" do |minikube|
      minikube.vm.box = "geerlingguy/centos7"
      #minikube.vm.network "private_network", type: "dhcp"
      minikube.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      #minikube.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
      #minikube.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "dhcp"
      #minikube.vm.network "hostonly", "10.0.0.4"
      #minikube.vm.network "private_network", ip: "10.0.0.10"
      minikube.vm.hostname = "minikube"
      minikube.vm.provider "virtualbox" do |v|
        v.name = "minikube"
        v.memory = 4096
        v.cpus = 2
      end
      minikube.vm.provision :shell do |shell|
        shell.path = "install_minikube.sh"
        shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
      end
    end
  end

  